### ISSUE TITLE
HazelcastMQCamelConsumer doesn't support suspend

### ISSUE THREAD

**Issue by nhoughto** [mpilone/hazelcastmq#11]
The camel consumer class only implements the start/stop methods, and not the extra suspend interface. This means in some scenarios during a graceful shutdown messages can be read off the queue and passed onto the route while a shutdown is occurring, causing failures like "no consumers available for route X".

My understanding of the graceful shutdown procedure is that all routes are first suspended and then shutdown once there are no more exchanges in-flight. Error are generated because other components like Direct etc honour the suspend as well as the shutdown. I think all you have to do is implement SuspendableService in the MQConsumer and call stop() ? Can you call start() again once you call stop()?

More details here: http://camel.apache.org/lifecycle.html

thanks!

**Comment by mpilone** [comment]
Sounds simple enough. I'll take a look at it.

**Comment by mpilone** [comment]
Should be implemented now in the 1.5 develop branch.
